### ISSUE TITLE
BeatSage-Downloader Issue

### ISSUE THREAD

**Issue by june231969** [BadgerHobbs/BeatSage-Downloader#1]
![Beat Sage Downloader Issue](https://user-images.githubusercontent.com/19434012/82482041-3acc4100-9aa4-11ea-8704-d6c86a92bb0e.png)

I am experiencing the issue shown in the photo after a minute or so of queuing up any number of songs.  I am using Windows 7.

**Comment by BadgerHobbs** [comment]
Please contact me via the Beatsage Discord https://discord.beatsage.com/ as I will be able to help you better there.
