### ISSUE TITLE
unable to retrieve metadata

### ISSUE THREAD

**Issue by mvk222** [BadgerHobbs/BeatSage-Downloader#5]
no matter what youtube link i feed the program, it keeps telling me "unable to retrieve metadata" and stops downloading.
does anybody know how to fix that?

<img width="797" alt="Bildschirmfoto 2020-06-08 um 13 19 03" src="https://user-images.githubusercontent.com/66204631/84024825-d9a0da80-a98a-11ea-88af-c94ac9db84c7.png">

**Comment by BadgerHobbs** [comment]
If you have 'Local YouTube Download' enabled, please disable it (or vice versa)

**Comment by mvk222** [comment]
thanks a lot, that worked
great app by the way!
