### ISSUE TITLE
Question about adding song cues

### ISSUE THREAD

**Issue by ayutaz** [BadgerHobbs/BeatSage-Downloader#9]
I use it all the time. Thank you very much.
How can I change the number of queues to add?
I briefly read through the app settings, but I couldn't figure out where to find mine.

**Comment by BadgerHobbs** [comment]
Glad you enjoy it!

The maximum queue length is set to 100 songs as an agreement with the BeatSage developers to prevent constant server overloads (e.g. people queuing 1000s of songs continually), so as a result cannot be changed.

Given it takes a good while to go through that many songs, I'd recommend just leaving it running and then delete the completed items and re-add more. You can always copy the playlist imported list in the add downloads window to a text editor such as notepad++, then paste them into the import list in sections until none left.

**Comment by ayutaz** [comment]
Thank you for your reply.
I guess I can't add more than 100 due to BeatSage's limitation.
I would like to handle more than 100 songs by adding them to a text editor.
